### ISSUE TITLE
无法搜索

### ISSUE THREAD

**Issue by 0123cf** [amap-demo/JSAPI-simple-placesearch-mobile#1]
Without changing the code, the input text does not have a drop-down selection.
Was the upload wrong?
没有改代码的情况下，输入文字并不会出现下拉选择。
demo是不是上传错了？

**Comment by monkeym4ster** [comment]
I have same question.

**Comment by monkeym4ster** [comment]
@0123cf Did you solve it?

**Comment by monkeym4ster** [comment]
I solved the problem.
Just change the API key...😂
